services:
  kea-ui:
    build: .
    environment:
      CONFIG_FILE: /config/config.json

    volumes:
      - ./configs/config.json:/config/config.json:ro

    ports:
      - "8080:8080"

    restart: unless-stopped
